import type { DiscoveryUser } from '../api/discovery-api';

export const discoveryDemoUsers: DiscoveryUser[] = [
  {
    id: 'demo-user-2',
    username: 'sam',
    avatar: '',
    nativeLanguage: 'English',
    targetLanguage: 'Japanese',
    languageLevel: 'B1',
    learningGoal: 'Daily conversation',
    bio: 'Morning language swaps with coffee and casual news topics.',
    timezone: 'Asia/Tokyo',
    matchReasons: ['Language exchange match: English ↔ Japanese', 'Same level: B1'],
    relationshipStatus: 'stranger',
  },
  {
    id: 'demo-user-3',
    username: 'lina',
    avatar: '',
    nativeLanguage: 'Mandarin',
    targetLanguage: 'English',
    languageLevel: 'B2',
    learningGoal: 'Business communication',
    bio: 'UX designer practicing product reviews, meetings, and presentation flow.',
    timezone: 'Asia/Shanghai',
    matchReasons: ['Native Mandarin speaker for your Mandarin', 'Nearby level: B2'],
    relationshipStatus: 'request_sent',
  },
  {
    id: 'demo-user-4',
    username: 'noa',
    avatar: '',
    nativeLanguage: 'Spanish',
    targetLanguage: 'Japanese',
    languageLevel: 'A2',
    learningGoal: 'Travel practice',
    bio: 'Planning a spring trip and looking for relaxed phrase practice.',
    timezone: 'Europe/Madrid',
    matchReasons: ['Also learning Japanese', 'Travel practice'],
    relationshipStatus: 'request_received',
  },
  {
    id: 'demo-user-5',
    username: 'mina',
    avatar: '',
    nativeLanguage: 'Korean',
    targetLanguage: 'English',
    languageLevel: 'B1',
    learningGoal: 'Culture exchange',
    bio: 'Enjoys music, food, and short daily check-ins after work.',
    timezone: 'Asia/Seoul',
    matchReasons: ['Also learning English', 'Same level: B1'],
    relationshipStatus: 'friend',
  },
  {
    id: 'demo-user-6',
    username: 'hugo',
    avatar: '',
    nativeLanguage: 'French',
    targetLanguage: 'English',
    languageLevel: 'C1',
    learningGoal: 'Business communication',
    bio: 'Wants sharp feedback on interviews, negotiation, and concise writing.',
    timezone: 'Europe/Paris',
    matchReasons: ['Also learning English', 'Similar learning goal: Business communication'],
    relationshipStatus: 'stranger',
  },
  {
    id: 'demo-user-7',
    username: 'aya',
    avatar: '',
    nativeLanguage: 'Japanese',
    targetLanguage: 'English',
    languageLevel: 'B1',
    learningGoal: 'Daily conversation',
    bio: 'Likes slow conversation practice with corrections in both directions.',
    timezone: 'America/Los_Angeles',
    matchReasons: ['Also learning English', 'Same level: B1'],
    relationshipStatus: 'stranger',
  },
];
